### ISSUE TITLE
Support llvm-17/16/15 on Macos

### ISSUE THREAD

**Issue by msclock** [aminya/setup-cpp#243]
Brew has formulas about llvm-17/16/15/14, see <https://github.com/Homebrew/homebrew-core/blob/master/Formula/l/llvm.rb>

But in setup-cpp indicates llvm-17/16/15 are missing in 

https://github.com/aminya/setup-cpp/blob/17a5a833c411175bd64ad1df88965b29b74b1a4b/src/llvm/llvm_url.ts#L103-L121

## Upvote & Fund

@aminya is using [Polar.sh](https://polar.sh/aminya) so you can upvote and help fund this issue. The funding is received once the issue is completed & confirmed by you.

Thank you in advance for helping prioritize & fund our backlog!

<br/>

<a href="https://polar.sh/aminya/setup-cpp/issues/243">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/aminya/setup-cpp/issues/243/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/aminya/setup-cpp/issues/243/pledge.svg">
</picture>
</a>

**Comment by aminya** [comment]
This has been on my TODO list.  See #242. 

## Upvote & Fund

@aminya is using [Polar.sh](https://polar.sh/aminya) so you can upvote and help fund this issue. The funding is received once the issue is completed & confirmed by you.

Thank you in advance for helping prioritize & fund our backlog!

<br/>

<a href="https://polar.sh/aminya/setup-cpp/issues/243">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/aminya/setup-cpp/issues/243/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/aminya/setup-cpp/issues/243/pledge.svg">
</picture>
</a>

**Comment by msclock** [comment]
@aminya thanks for your rapid feedback. Excellent work👍

**Comment by ClausKlein** [comment]
### I can not understand why it does not work on Darwin:
```bash
bash-5.2$ sudo ./setup-cpp-x64-macos --compiler llvm-18  
Invalid semver version 18 used for the compiler.
::group::Installing llvm 18
Coerced version '18' to '18.0.0'
Installing llvm 18 x64 via direct downloading
Error: Unsupported target! (platform='darwin', version='18'). Try one of the following: {}
::endgroup::
took 0 seconds
Failed to install the llvm-18
setup-cpp finished
Run `source ~/.cpprc` or restart your shell to update the environment.
bash-5.2$ sudo ./setup-cpp-x64-macos --compiler llvm-17
Invalid semver version 17 used for the compiler.
::group::Installing llvm 17
Coerced version '17' to '17.0.0'
Installing llvm 17 x64 via direct downloading
Error: Unsupported target! (platform='darwin', version='17'). Try one of the following: {}
::endgroup::
took 0 seconds
Failed to install the llvm-17
setup-cpp finished
Run `source ~/.cpprc` or restart your shell to update the environment.
bash-5.2$ 
```

**Comment by ClausKlein** [comment]
### Today, setup-cpp install llvm-14 by default, that is not helpflully!
```bash
bash-5.2$ clang --version
Homebrew clang version 17.0.6
Target: x86_64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
bash-5.2$ 
```

**Comment by msclock** [comment]
> ### Today, setup-cpp install llvm-14 by default, that is not helpflully!
> ```shell
> bash-5.2$ clang --version
> Homebrew clang version 17.0.6
> Target: x86_64-apple-darwin23.4.0
> Thread model: posix
> InstalledDir: /usr/local/opt/llvm/bin
> bash-5.2$ 
> ```

at least 15 should be installed.🧐

**Comment by ClausKlein** [comment]
No, I need at least 17 for C++ modules!

**Comment by aminya** [comment]
There are no official LLVM binaries for x86 on Apple after LLVM 16. Brew builds LLVM from the source, which I consider impractical for day-to-day usage. 

However, I am planning to add support for Apple ARM

**Comment by msclock** [comment]
> There are no official LLVM binaries for x86 on Apple after LLVM 16. Brew builds LLVM from the source, which I consider impractical for day-to-day usage.
> 
> However, I am planning to add support for Apple ARM

And is it practical to consider to use brew to install llvm-17/16 🫤

**Comment by msclock** [comment]
I have adopted the above workaround temporarily in macos-12 and it work [here](https://github.com/serious-scaffold/ss-cpp/actions/runs/8645856705/job/23703966694#step:5:1).

**Comment by msclock** [comment]
I have adopted the above workaround temporarily in macos-12 and it works [here](https://github.com/serious-scaffold/ss-cpp/actions/runs/8645856705/job/23703966694#step:5:1).

**Comment by aminya** [comment]
The reason it works seems to be because you didn't specify a version, and some version is already cached/installed on the system:
https://github.com/serious-scaffold/ss-cpp/actions/runs/8645856705/job/23703966694#step:5:18

Otherwise, it would take hours to compile Z3 and LLVM from the source for x86 if you try this on some other runner or locally.

I think there are some things we can do to reuse the already cached installations and error out for other versions.  For Arm, this is totally solvable by using the official binaries.
